### ISSUE TITLE
 Dialogs quality issues: replace png icons by svg ones 

### ISSUE THREAD

**Issue by DelazJ** [qgis/qgis3_UIX_discussion#12]
Throughout QGIS, dialogs have quality problems. It would be nice if someone could check all dialogs for the following problem: **Check through and delete unused png icons**.

A lot of the old png icons have been replaced with proper svg versions, but the pngs are still included and in some cases they are incorrectly used instead of the svg replacements.

Identifying these would be a matter of going though each png icon in the repo and searching through the code (eg via "git grep mactionrefresh.png") to see if they are still used anywhere. (Ignore any hits in the resources files!) . If they aren't they can be safely removed. If they are, you could check whether a suitable svg replacement can be used.

The more pngs we remove the easier it will be to identify which remaining icons require vector versions

Reported by @nyalldawson

**Comment by DelazJ** [comment]
Note that in some cases, a svg icon exists but do not have same name, e.g. [mActionRefresh](https://github.com/qgis/QGIS/blob/master/images/themes/default/mActionRefresh.png) vs [mActionDraw](https://github.com/qgis/QGIS/blob/master/images/themes/default/mActionDraw.svg)

**Comment by pcav** [comment]
Love these clean-ups, thanks a lot.

**Comment by SrNetoChan** [comment]
@nyalldawson, a fast search showed me lots of different folders with PNG files. Can you tell me which are the ones we should care about? For example, the tests folder have lot's of PNGs but I think they are not a problem.

**Comment by SrNetoChan** [comment]
@pcav These are just ideas, someone will have to pick them up and fix it :-)

**Comment by nyalldawson** [comment]
@SrNetoChan

https://github.com/qgis/QGIS/tree/master/images/themes/default

And subfolders

**Comment by SrNetoChan** [comment]
Is there a validade reason to keep old themes? Thanks

**Comment by SrNetoChan** [comment]
@nyalldawson Sorry to bother, again. I'm looking into this. Got a list with all existing PNG files, now what folders should search? src only? If I remember I can ignore qrc files, right? Thanks

**Comment by DelazJ** [comment]
@SrNetoChan Begin with the ui files in https://github.com/qgis/QGIS/tree/master/src/ui: the idea is to replace any link to png file by its vectorized version (svg) if available. 
> Is there a validade reason to keep old themes? Thanks

I think it's also time, if we don't delete them (old themes and not used icons) yet, at least move them outside this folder to an archive folder

**Comment by SrNetoChan** [comment]
@DelazJ AFAIK, there are other ways to use icons without they be in UI files, that's why I asked.

**Comment by nyalldawson** [comment]
@SrNetoChan

You'll need to check the src folder (including the src/ui and src/plugins subfolders), and python/plugins and all subfolders.

**Comment by DelazJ** [comment]
Fixed
