### ISSUE TITLE
Widget's values are changed by mistake while scrolling dialogue with mouse wheel

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/qgis3_UIX_discussion#21]
Most of our dialog's widgets can be controlled by the mouse wheel. While this can be useful, IMHO it's the origin of some undesired changes in settings, as when you try to scroll down the dialog it self, if the mouse stops over a widget it will change its values and the user might not see it.

I wonder if there is a way to avoid this. Would we need to disable mouse scrolling on widgets?

**Comment by DelazJ** [comment]
Fixed in https://github.com/qgis/QGIS/commit/aad182fdc041bd5e83be5b2b399cae496826c008
