### ISSUE TITLE
The Evis Event browser dialog might need some love

### ISSUE THREAD

**Issue by DelazJ** [qgis/qgis3_UIX_discussion#29]
This dialog might need some love IMO (note that i'm not a Evis user):
* some options are too much verbose: what about using tooltip and shorter label?
* are the "remember this" options needed? Why not saving the setting by default?
* and all these "reset" buttons? I also wonder if the use of push buttons instead of tool buttons is the most appropriate.
* items alignment/spacing could also be improved
![image](https://cloud.githubusercontent.com/assets/7983394/22043999/ad4dc21a-dd12-11e6-8bea-776d79a16801.png)

**Comment by pcav** [comment]
Not quite sure this is worth the while, given that evis AFAIK will be removed.
Tab order is wrong in other dialogs, probably better concentrate on these.
Thanks.

**Comment by DelazJ** [comment]
@pcav 
> Not quite sure this is worth the while, given that evis AFAIK will be removed.

I was not aware of this. Any discussion or issue report to point me to?
> Tab order is wrong in other dialogs, probably better concentrate on these.

Not sure why you mention tab ordering as it's not an issue here but you may want to give a look to qgis/QGIS#4013

**Comment by pcav** [comment]
Removing evis is a part of the general cleanup for Q3. I do not have a ref at hand now, but commit should be visible.
Sorry for misunderstanding the tab issue (I really should not work from the phone ;) ).

**Comment by DelazJ** [comment]
No worries. Thanks. Closing.

**Comment by DelazJ** [comment]
Actually, I found https://github.com/qgis/qgis3.0_api/issues/67 and http://osgeo-org.1560.x6.nabble.com/should-core-plugins-not-be-available-in-plugin-manager-tt5299556.html but none clearly claiming the removal of the plugin (but pythoning it and cleaning UI)

**Comment by DelazJ** [comment]
eVIS has finally gone
