### ISSUE TITLE
Vector Style: Reorganize polygon symbol layers options

### ISSUE THREAD

**Issue by DelazJ** [qgis/qgis3_UIX_discussion#41]
A proposal to reorder options provided in symbol layer dialog
### Simple Fill
1. Fill
1. Fill style
3. Stroke
4. Stroke Width
5. Stroke Style
6. Join Style
8. Offset

### SVG Fill
1. Texture width
1. Fill
3. Stroke
4. Stroke Width
5. Rotation
8. SVG Groups / Symbols

**Comment by rduivenvoorde** [comment]
@DelazJ hi H, testing gitter hooks

**Comment by DelazJ** [comment]
Implemented
