### ISSUE TITLE
Move 'Plugins/Install plugin from zip' to the 'Manage and install Plugins ' dialog

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/qgis3_UIX_discussion#48]
I think installing a plugin from a local zip is not 'average' use. So I would prefer to move this away from the Plugins menu item to ... I don't know maybe in the dialog? Something like this:

![dialog](https://user-images.githubusercontent.com/731673/31575341-a8995d32-b0e4-11e7-9659-45dc96d18b33.png)

@alexbruy what do you think? Of was it a deliberate choice to make it an actual menu action

ps I normally create a symbolic link to the development folder when I'm developnig

**Comment by Gustry** [comment]
+1 for me. The dialog is called "Manage and install plugins", it makes more sense for me to have this option in there.

**Comment by alexbruy** [comment]
@rduivenvoorde not sure this is a good UX to have an almost empty dialog page with just file selector on it.

**Comment by rduivenvoorde** [comment]
![plugins install plugin from zip _126](https://user-images.githubusercontent.com/731673/31583460-c2847bc4-b19c-11e7-89db-ff6f5cf184d8.png)

@alexbruy, thanks for your comment. Yes maybe you are right. I started of (see screenshot above), and then realised that the 'buttons' on the right are actually tabs, so every 'tab' need a page...

One thing we could do is show the list of all plugins (like in the screenie), and upon selecting the tab immidialty show the file selector (instead of a button in between). The tab then 'acts like a button'. Not sure if that is 'natural' or good ui though...

Another option is have an extra button in this page (either swap the Search one with a button, OR add one below where you now see all the disabled buttons see).

@alexbruy another observation I had recently, if you hit just enter when you have some plugins upgradable, they all start upgrading (while you are NOT in the Upgradable tab)...
And when you switch between tabs, the dialog title does not always follow, sometimes you need to click twice on the tab.

This is not VERY important to me, it is just that I want to clean up the starting interface a little for new users....

**Comment by borysiasty** [comment]
@rduivenvoorde @alexbruy 

I guess an empty page with the single button and a text explaining what it is for will be much better than a file dialog unexpectedly popping up. Most users won't install plugins from files, so a short explanation is justified.

I also considered embedding the file dialog into the page, but it would look a bit weird and unexpected I guess...

Regarding the last option with a button in the bottom of the dialog - I would place it next to the Help button, and also move "Upgrade all" and "Settings" there (not one line above, as they are not related to the currently selected plugin). But generally I prefer the former option, as more readable.

> And when you switch between tabs, the dialog title does not always follow, sometimes you need to click twice on the tab.

This is strange. Can you recall any special conditons when it occurs?

**Comment by borysiasty** [comment]
@rduivenvoorde @alexbruy something like that:

https://github.com/qgis/QGIS/pull/5372

What do you think? Of course the text might be better and especially longer - I'm not good in waffling :)

**Comment by borysiasty** [comment]
@rduivenvoorde - ok I can reproduce the bug you reported. Will look at it.

**Comment by rduivenvoorde** [comment]
@borysiasty I'm good in waffling :-) But I'm also afraid to do things others would not like ... Maybe taking too small steps :-(
Thanks for having a look into the update/tab issue too!

**Comment by borysiasty** [comment]
@rduivenvoorde: who could protest agains filling the ugly empty space with a long text that nobody is going to read? :) For translators it's a pleasant break between all the untranslateable compact and meaningful phrases. 

Anyway, for now I've merged it, so you can close the ticket I guess.

**Comment by DelazJ** [comment]
Thanks @borysiasty
