### ISSUE TITLE
New sequence of Vector layer properties dialog?

### ISSUE THREAD

**Issue by DelazJ** [qgis/qgis3_UIX_discussion#51]
Trying to find an order for the vector layer properties dialog tabs. This is based on what I often use, trying to "group" features that somehow look alike, and what I think "**_average users_**" (don't know who they are! so assimilate them to myself 😄  ) will be looking for:

1. Information
2. Source
3. ~~Metadata~~ Symbology
4. ~~Symbology~~ Labels
5. ~~Labels~~ Diagrams
6. 3D View
7.  Fields
8. Forms
9. ~~Rendering~~ Joins
10. ~~Display~~ Auxiliary Storage
11. Actions
12. ~~Joins~~ Display
13. ~~Diagrams~~ Rendering
14. Variables
15. ~~Legend~~ Metadata
16. Dependencies
17. ~~QGIS Server~~ Legend
18. ~~Auxiliary Storage~~ QGIS Server

Comments? I realized that Metadata has been pushed again to the bottom (which could be unfortunate?). @Gustry @nyalldawson @nirvn @m-kuhn

**Comment by Gustry** [comment]
+1 for me. I totally agree that styling, labeling must be on top.
Will you do the same for the raster dialog? (but metadata more or less at the same place)
